# --- Environnement ---
NUM_DRONES = 3
NUM_INTRUDERS = 1
SPAWN_AREA = (50, 1, 50)
UNITY_PORT = 9000
NUM_PARALLEL_ENVS = 1
USE_VECENV = False
USE_SUBPROC_VECENV = False

# --- Patrouille & Détection ---
DETECTION_RADIUS = 25.0
GRID_SIZE = 20
COVERAGE_RADIUS = 5.0
ZONE_MIN_X, ZONE_MAX_X = -50.0, 50.0
ZONE_MIN_Z, ZONE_MAX_Z = -50.0, 50.0

# --- Récompenses ---
REWARD_COVERAGE = 5.0  # Augmenté de 2.0 à 5.0 (+150%) pour encourager l'exploration
REWARD_DETECTION = 150.0
REWARD_OVERLAP_PENALTY = -0.05
REWARD_COLLISION_PENALTY = -12.0
REWARD_INTRUDER_COLLISION_PENALTY = -0.5
REWARD_DISTANCE_PENALTY = -0.03

TRACKING_RADIUS = 35.0
TRACKING_REWARD = 1.5
CAPTURE_RADIUS = 20.0
CAPTURE_DRONES_REQUIRED = 1
REWARD_CAPTURE = 400.0

ZONE_BOUNDARY_MARGIN = 5.0
REWARD_OUT_OF_ZONE_PENALTY = -4.0
REWARD_BOUNDARY_WARNING = -0.1
REWARD_IN_ZONE = 0.5  # Augmenté pour être visible après scaling
ZONE_TRUNCATION_MARGIN = 5.0

REWARD_CENTRAL_ALERT = 20.0
CENTRAL_ALERT_COOLDOWN = 10

MIN_DRONE_SEPARATION = 3.5
OPTIMAL_DRONE_SEPARATION = 10.0
MAX_DRONE_SEPARATION = 30.0
REWARD_GOOD_SEPARATION = 0.05
REWARD_TOO_CLOSE_PENALTY = -0.1
REWARD_TOO_FAR_PENALTY = -0.05

OBSTACLE_COLLISION_RADIUS = 5.0
REWARD_OBSTACLE_COLLISION_PENALTY = -1.0
REWARD_OBSTACLE_NEAR_PENALTY = -0.01
OBSTACLE_NEAR_THRESHOLD = 7.0

# --- MARL Hyperparamètres ---
EPISODES = 1500
MAX_STEPS_PER_EPISODE = 750  # Augmenté de 500 à 750 pour permettre plus d'exploration avant capture
LEARNING_RATE = 0.00005
GAMMA = 0.95

# --- Curriculum Learning ---
CURRICULUM_ENABLED = True
CURRICULUM_START_STAGE = 0

# Stage 0 : Focus Pursuit (plus permissif)
CURRICULUM_STAGE0_INTRUDER_SPEED_MULT = 0.7
CURRICULUM_STAGE0_RADIUS_MULT = 2.0
CURRICULUM_STAGE0_ENABLE_COVERAGE = True  # activé dès le départ
CURRICULUM_STAGE0_ENABLE_OBSTACLES = False
CURRICULUM_STAGE0_ENABLE_ZONE = False
CURRICULUM_STAGE0_ENABLE_SEPARATION = False
CURRICULUM_STAGE0_ENABLE_CENTRAL_ALERT = False
CURRICULUM_STAGE0_ENABLE_DISTANCE_PENALTY = True

# Stage 1 : Obstacles + Zone
CURRICULUM_STAGE1_INTRUDER_SPEED_MULT = 0.9
CURRICULUM_STAGE1_RADIUS_MULT = 1.2
CURRICULUM_STAGE1_ENABLE_COVERAGE = False
CURRICULUM_STAGE1_ENABLE_OBSTACLES = True
CURRICULUM_STAGE1_ENABLE_ZONE = True
CURRICULUM_STAGE1_ENABLE_SEPARATION = False
CURRICULUM_STAGE1_ENABLE_CENTRAL_ALERT = True
CURRICULUM_STAGE1_ENABLE_DISTANCE_PENALTY = True

# Stage 2 : Complet
CURRICULUM_STAGE2_INTRUDER_SPEED_MULT = 1.0
CURRICULUM_STAGE2_RADIUS_MULT = 1.0
CURRICULUM_STAGE2_ENABLE_COVERAGE = True
CURRICULUM_STAGE2_ENABLE_OBSTACLES = True
CURRICULUM_STAGE2_ENABLE_ZONE = True
CURRICULUM_STAGE2_ENABLE_SEPARATION = True
CURRICULUM_STAGE2_ENABLE_CENTRAL_ALERT = True
CURRICULUM_STAGE2_ENABLE_DISTANCE_PENALTY = True

# Critères de progression
CURRICULUM_STAGE0_SUCCESS_RATE_THRESHOLD = 0.7
CURRICULUM_STAGE0_MIN_EPISODES = 50
CURRICULUM_STAGE0_MIN_TIMESTEPS = 50000
CURRICULUM_STAGE0_DETECTION_RATE_THRESHOLD = 0.7
CURRICULUM_STAGE0_TRACKING_RATE_THRESHOLD = 0.7
CURRICULUM_STAGE0_STABILITY_THRESHOLD = 0.40

CURRICULUM_STAGE1_SUCCESS_RATE_THRESHOLD = 0.7
CURRICULUM_STAGE1_MIN_EPISODES = 50
CURRICULUM_STAGE1_MIN_TIMESTEPS = 50000
CURRICULUM_STAGE1_DETECTION_RATE_THRESHOLD = 0.7
CURRICULUM_STAGE1_TRACKING_RATE_THRESHOLD = 0.7
CURRICULUM_STAGE1_STABILITY_THRESHOLD = 0.40

CURRICULUM_EVALUATION_WINDOW = 20

# --- Reward Scaling ---
REWARD_SCALING_ENABLED = True
REWARD_SCALING_FACTOR = 0.05  # Augmenté pour avoir plus de visibilité sur ep_rew_mean

# --- Checkpointing ---
CHECKPOINT_SAVE_FREQ = 10000
CHECKPOINT_DIR = "checkpoints"

# --- Reconnexion Unity ---
UNITY_RECONNECT_ENABLED = True
UNITY_RECONNECT_MAX_ATTEMPTS = 5
UNITY_RECONNECT_DELAY = 2.0
UNITY_SOCKET_TIMEOUT = 10

# --- Sauvegarde ---
SAVE_DIR = "models"
MODEL_NAME = "ppo_marl"

# --- Logging ---
LOG_DIR = "logs"
TENSORBOARD_LOG_DIR = "logs/tensorboard"
EVALUATION_LOG_DIR = "logs/evaluation"

# --- Vitesse d'Exécution ---
DRONE_MOVE_SPEED = 0.5
INTRUDER_MOVE_SPEED = 1.5
STEP_DELAY = 0.2
